#pragma once

#include <QMainWindow>
#include <memory>
#include "TelemetryModel.h"
#include "DroneSimulator.h"
#include "DroneWorker.h"

QT_BEGIN_NAMESPACE
namespace Ui
{
    class MainWindow;
} // Forward declaration for the UI generated by Qt Designer.
QT_END_NAMESPACE

// Main window class responsible for UI display and control logic.
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr); // Constructor: Initializes the main window and UI components.
    ~MainWindow() override;                // Destructor: Cleans up the UI and managed resources.

private slots:
    void onTelemetryUpdated();                   // Slot: Updates the UI display with new telemetry data from the model.
    void onStartClicked();                       // Slot: Handles the button press to start the drone simulation.
    void onStopClicked();                        // Slot: Handles the button press to stop the drone simulation.
    void onSimulateFailureToggled(bool checked); // Slot: Handles the checkbox state change for simulating a drone failure.
    void onStrategyChanged(int idx);             // Slot: Handles selection change for movement strategy (e.g., hover).
    void appendLog(const QString &entry);        // Slot: Appends a new message to the log display area.

private:
    Ui::MainWindow *ui;          // Pointer to the compiled UI object (all the widgets).
    TelemetryModel *m_model;     // Model holding the current drone telemetry data.
    DroneSimulator *m_simulator; // The core simulation object generating data.
    DroneWorker *m_worker;       // The thread managing the execution of the simulator.
};